files/logstash-configs/24-nagios.conf

Refer to the epoch timestamp from the actual log event, rather than
trusting the '@timestamp' field automatically created by Logstash. The
latter stamps the time of log ingestion, not the time of the event.

Updates timestamp in Nagios log parsing

---

files/logstash-configs/21-ssh-logins.conf

Feedback from @garrettr and myself is that failed SSH login alerts amount to non-useful noise.

Remove Slack alerts for failed SSH logins

---

molecule.yml

By default tests should run under Debian 8. Ubuntu Wily is still available, just use the `--platform` option on the test step for molecule. Closes #29.

Defaults to Debian 8 in test suite

---

files/logstash-configs/18-fail2ban.conf
files/logstash-patterns/fail2ban

This log is very simple to parse. The filter includes tags for ban and unban actions, plus geolocation.

Fail2ban log parsing

---

files/logstash-configs/22-redmine.conf

Error in logstash.log:
```{:timestamp=>"2016-04-21T16:59:48.782000-0700", :message=>"Failed parsing date from field", :field=>"redmine_timestamp", :value=>"2016-04-21 16:59:39 -0700", :exception=>"Invalid format: \"2016-04-21 16:59:39 -0700\" is malformed at \"-0700\"", :config_parsers=>"yyyy-MM-dd HH:mm:ss z", :config_locale=>"default=en_US", :level=>:warn}```

Fix parsing of redmine_timestamp offset

---

files/logstash-configs/23-ufw.conf

Changes were introduced in 0bb1e2ffdda956594d05e4ffe224f238210e43e8,
adding custom patterns for UFW. In order to use custom patterns, the
directory housing the them must be explicitly declared in the grok
stanza referencing them. Fixed.

Adds missing patterns.d directory include for ufw filters

---

files/logstash-configs/40-metrics-monitoring.conf

The 80% value was mostly used during testing and isn't actually all that
useful. The long-term solution would be to make the threshold a var, so
it can be customized at will, but doing so will require converting the
logstash configs to templates, which will take a bit of work.

Bumps diskspace warning threshold 80 -> 90%

---

files/logstash-configs/41-daily-metrics.conf

Assumes the Topbeat period is 60, so there will be an update within a minute after 12 noon.
Uses Ruby filter to handle typing and timing.
Replacing the `message` field makes the original Topbeat message hard to debug, so it's advisable to make a new field called `alert_message` and tell Riemann to use that. Requires updating the Riemann config.

Daily host metrics posted to Slack

---

defaults/main.yml
spec/elasticsearch_spec.rb
tasks/elasticsearch.yml

The elasticsearch service logs warning messages if generous ulimits for memlock are not configured (see #10). This PR implements unlimited soft and hard limits for `memlock` specifically for the `elasticsearch` user.
There are also limits configured to raise the number of open files permissible, which is essential for a system running both logstash and elasticsearch. Right now it's setting a sane limit for `nofile` of 65535. This is a judgment call, trying to strike a balance between the system default (1024) versus something much higher, such as 200000 or unlimited. If admins want a higher limit, they can simply override the middle-of-the-road value via default vars.
Closes #10.

Sets pam limits for elasticsearch user

---

README.md
examples/writing-filters/01-input.conf
examples/writing-filters/22-foo.conf
examples/writing-filters/99-output.conf

Setting up a decent dev environment for logstash filters is a pain, but these example files make it much easier. This is precisely what I use when writing new filters, and having templates in the repo makes it convenient to fall back to a clean slate between filter versions.
There are already a few resources linked to in the README, but these example files are much simpler to get started with.
Closes #27.

Documents development workflow for writing logstash filters

---

files/logstash-configs/22-redmine.conf
files/logstash-patterns/redmine

When the wrong key is used to send email to support@freedom.press, or PGP
ciphertext encrypted to the wrong key is embedded in a contact form submission,
the ticket will be discarded. We should be tagging and alerting on this so that
we can attempt to recover the information.

Catch and alert when Redmine_OpenPGP fails to decrypt message

---

files/logstash-configs/01-lumberjack-input.conf
meta/main.yml

The upstream freedomofpress.generate-ssl-cert role now supports
fine-grained permissions management. Rather than place the certificate
and keyfile for the Logstash service in the system-wide CA directory,
place them in the Logstash config directory with permissions on the key
so that it is readable by the "logstash" user.
Requires a hard-coded change to the Logstash input config, since the
config files are not yet templatized, meaning no vars can be interpolated.

Adds custom filepath for OpenSSL certificate and key

---

files/logstash-configs/21-ssh-logins.conf

Most notably leverages `break_on_match => false` for the SSH logins, to ensure that all possible matches are tried. Otherwise, the filter will bail out early and leave the `_grokparsefailure` tag assigned. Additionally filtering the syslog events to ensure that the date-parsing logic (#33) for SSH events only applies to events already tagged as "ssh".

Refines alerting strategy for SSH logins

---

files/logstash-configs/25-tor.conf
files/logstash-patterns/tor

Per OSSEC alerts reported by SecureDrop admins, general crawling of the Tor
network, including with OnionScan, and logs aggregated by FPF, there are
frequent connection attempts to hidden services on ports other-than-specified.
These result in a warning in the Tor log:
`[warn] connection_edge_process_relay_cell (at origin) failed.`
This commit adds parsing for an associated info-level logline so we can analyze
these trends and the port numbers that are being tried in ELK.

Parse connection attempts to hidden services on wrong ports

---

handlers/main.yml
spec/elasticsearch_spec.rb
tasks/elasticsearch.yml

Builds on the approach started in #10 and #31 to permit the elasticsearch service to lock memory greedily. Simply setting the `mlockall: true` in the elasticsearch YAML config is not sufficient; this PR updates systemd init files and default env vars as well.
The handlers file has been reordered. Take a look at 4a8d0b7 to understand why—briefly, Ansible runs handlers in the order they are declared, not in the order they are notified. Therefore the reorder is necessary to ensure that the daemon-reload handler runs first, prior to any service restarts.
Closes #42.

Allows elasticsearch to lock unlimited memory

---

tasks/logstash.yml

The read-only task for registering a list of installed logstash plugins
must run in order for the subsequent task that inspects the list results
to complete. This single, one-line change enables the entire role to be
run with the --check option (assuming it's already been applied once).

Supports dry run mode via --check playbook flag

---

README.md
defaults/main.yml
spec/elasticsearch_spec.rb
spec/kibana_spec.rb
spec/logstash_spec.rb
tasks/elasticsearch.yml
tasks/java.yml
tasks/kibana.yml
tasks/logstash.yml
tasks/main.yml
tasks/nginx.yml
tasks/packages.yml
templates/kibana.service.j2

Updates the role to use Elastic's package repositories for installing Kibana instead of downloading the tarball, per issue #39.
Removes `elk_kibana_version`. The new version is 4.5 instead of 4.4.1.
Updates the spec tests.

Install Kibana from apt repositories instead of tarball

---

spec/kibana_spec.rb

The role created from scratch did not pass `molecule test`.
The default permissions for `/opt/kibana` are set to 775 and the Serverspec check was expecting 755:
```
vagrant@logserver:~$ ls -ld /opt/kibana
drwxrwxr-x 10 root root 4096 Aug  6 05:25 /opt/kibana
vagrant@logserver:~$
```

Fix check for default permissions for /opt/kibana to root:root 775

---

spec/kibana_spec.rb
tasks/kibana.yml

Why not? https://www.elastic.co/guide/en/kibana/current/releasenotes.html

Bumps Kibana version 4.5 -> 4.6

---

tasks/logstash.yml
tasks/ufw.yml

The old-style non-handlebars syntax has been deprecated since v2, and
breaks as of Ansible v2.2. Updating the with_items lines fixes.

Updates with_items syntax with explicit variable interpolation

---

defaults/main.yml
tasks/main.yml

This is necessary if upstream playbooks using this role are using different web server config and don't want this to clobber local changes.

Allow override of nginx task

---

spec/elasticsearch_spec.rb
spec/kibana_spec.rb
spec/logstash_spec.rb
tasks/logstash.yml

Updates Logstash to 2.3.x, also updates spec to reflect current Kibana and ElasticSearch versions.
I went through the Kibana/ES/Logstash 5.0 update and it's quite messy and destructive, would require massive changes to this role. These are the safest version bumps you can get while maintaining existing compatibility.

Various version updates for the stack

---

files/logstash-configs/13-nginx.conf
files/logstash-patterns/nginx

Uses some community-maintained patterns and a quick-and-dirty `type` of
"nginx" to trigger the parsing. Optimistically assuming that any
nginx-related log files will match one of two formats:
* `NGINXACCESS` (e.g. `/var/log/nginx/access.log`)
* `NGINXERROR` (e.g. `/var/log/nginx/error.log`)
Lazily using a single grok declaration to attempt matching against both
patterns. The upside here is simple reuse of the geoip logic; the
downside is that ES won't see discrete `nginx-access` and `nginx-error`
tags.

Adds Nginx log parsing logic

---

README.md
defaults/main.yml
tasks/logstash.yml

This field for the `geoip` filter is described [here]. This change
allows to optionally add a local geoip fileglob to the remote system.
Future addition should probably automate pulling this from another location
but punting on that for now.
[here]: https://www.elastic.co/guide/en/logstash/2.3/plugins-filters-geoip.html#plugins-filters-geoip-database

Add support for dropping GeoIP database files
